---

- name: Get running config of SRX 320
  gather_facts: yes
  hosts: jun
  connection: local

  vars:
    log_dir: "{{ playbook_dir }}/logs"
    ROLLBACK: "{{ 1 }}"
  
  #  vars_prompt:
  #    - name: "ROLLBACK"
  #      prompt: "Rollback ID to compare with active configuration"
  #      private: no

  tasks:
    - name: "Get committed configuration & Save the diffs"
      juniper.device.config:
        retrieve: "committed"
        format: "set"
        diff: true
        rollback: "{{ ROLLBACK }}"
        check: false
        commit: false
      register: response

    - name: "Print config"
      debug:
        var: response.config_lines

    - name: "Print config diff"
      debug:
        var: response.diff_lines
