---
- hosts: all
  become: no
  tasks:
    - name: Run shell cmd
      shell: |
        date
        hostname
        sleep 60
        date
      register: response
  
    - name: "Print output"
      debug:
        var: response.stdout_lines
