
---

- name: Get running config of SRX 320
  gather_facts: no
  hosts: all
  connection: local

  vars:
    log_dir: "{{ playbook_dir }}/logs"

  vars_prompt:
    - name: "ROLLBACK"
      prompt: "Rollback ID to compare with active configuration" 
      private: no

  tasks:
    - name: "Print config"
      debug:
        msg: "Hello world"



